<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.10" />
    <PackageReference Include="MSTest" Version="4.0.1" />
    <PackageReference Include="NBuilder" Version="6.1.0" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Compartilhado/" />
    <Folder Include="Compartilhado/Orm/" />
    <Folder Include="Modulos/" />
    <Folder Include="Modulos/ModuloCategoria/" />
    <Folder Include="Modulos/ModuloCompromisso/" />
    <Folder Include="Modulos/ModuloContato/" />
    <Folder Include="Modulos/ModuloTarefa/" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/eAgenda.Infra/eAgenda.Infra.csproj" />
  </ItemGroup>

</Project>
