@baseUrl = https://localhost:7098

### Cadastrar contato
# @name cadastrarContato
POST {{baseUrl}}/api/contatos
Content-Type: application/json

{
    "nome": "Junior Testes",
    "email": "teste-{{$guid}}@academiadoprogramador.net",
    "telefone": "(11) 99999-9999",
    "cargo": "Analista de Testes",
    "empresa": "Academia do Programador"
}

###
@contatoId = {{cadastrarContato.response.body.$.id}}

### Editar contato
PUT {{baseUrl}}/api/contatos/{{contatoId}}
Content-Type: application/json

{
    "nome": "Junior Testes Atualizado",
    "email": "teste-atualizado-{{$guid}}@academiadoprogramador.net",
    "telefone": "(11) 98888-3040",
    "cargo": "Suporte",
    "empresa": "Academia do Programador"
}

### Excluir contato
DELETE {{baseUrl}}/api/contatos/{{contatoId}}

### Listar contatos
GET {{baseUrl}}/api/contatos

### Selecionar contato por ID
GET {{baseUrl}}/api/contatos/{{contatoId}}
